version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    # gosimple: merged into staticcheck in golangci-lint v2
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    # typecheck: built-in to golangci-lint v2
    - unused # checks for unused constants, variables, functions and types
    ## disabled by default
    - asasalint # checks for pass []any as any in variadic func(...any)
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - bidichk # checks for dangerous unicode character sequences
    - bodyclose # checks whether HTTP response body is closed successfully
    - dupl # tool for code clone detection
    - copyloopvar
    - durationcheck # checks for two durations multiplied together
    - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
    - errorlint # finds code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - exhaustive # checks exhaustiveness of enum switch statements
    - forbidigo # forbids identifiers
    - gocheckcompilerdirectives # validates go compiler directive comments (//go:)
    - gochecksumtype # checks exhaustiveness on Go "sum types"
    - goconst # finds repeated strings that could be replaced by a constant
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    # goimports: moved to formatters section for golangci-lint v2
    - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard # allow and block lists linter for direct Go module dependencies
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
    - makezero # finds slice declarations with non-zero initial length
    - mirror # reports wrong mirror patterns of bytes/strings usage
    - musttag # enforces field tags in (un)marshaled structs
    - nakedret # finds naked returns in functions greater than a specified function length
    - nilerr # finds the code that returns nil even if it checks that the error is not nil
    - noctx # finds sending http request without context.Context
    - nolintlint # reports ill-formed or insufficient nolint directives
    - nosprintfhostport # checks for misuse of Sprintf to construct a host with port in a URL
    - perfsprint # checks that fmt.Sprintf can be replaced with a faster alternative
    - predeclared # finds code that shadows one of Go's predeclared identifiers
    - promlinter # checks Prometheus metrics naming via promlint
    - protogetter # reports direct reads from proto message fields when getters should be used
    - reassign # checks that package variables are not reassigned
    - revive # fast, configurable, extensible, flexible, and beautiful linter for Go, drop-in replacement of golint
    - rowserrcheck # checks whether Err of rows is checked successfully
    - sloglint # ensure consistent code style when using log/slog
    - sqlclosecheck # checks that sql.Rows and sql.Stmt are closed
    # stylecheck: merged into staticcheck in golangci-lint v2
    # tenv: removed in golangci-lint v2 (use usetesting instead)
    - testableexamples # checks if examples are testable (have an expected output)
    - testifylint # checks usage of github.com/stretchr/testify
    - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    - wastedassign # finds wasted assignment statements
    - whitespace # detects leading and trailing whitespace

  settings:
    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    exhaustruct:
      exclude:
        # std libs
        - "^net/http.Client$"
        - "^net/http.Cookie$"
        - "^net/http.Request$"
        - "^net/http.Response$"
        - "^net/http.Server$"
        - "^net/http.Transport$"
        - "^net/url.URL$"
        - "^os/exec.Cmd$"
        - "^reflect.StructField$"
        # public libs
        - "^github.com/Shopify/sarama.Config$"
        - "^github.com/Shopify/sarama.ProducerMessage$"
        - "^github.com/mitchellh/mapstructure.DecoderConfig$"
        - "^github.com/prometheus/client_golang/.+Opts$"
        - "^github.com/spf13/cobra.Command$"
        - "^github.com/spf13/cobra.CompletionOptions$"
        - "^github.com/stretchr/testify/mock.Mock$"
        - "^github.com/testcontainers/testcontainers-go.+Request$"
        - "^github.com/testcontainers/testcontainers-go.FromDockerfile$"
        - "^golang.org/x/tools/go/analysis.Analyzer$"
        - "^google.golang.org/protobuf/.+Options$"
        - "^github.com/DataDog/datadog-api-client-go/v2/api/datadog\\.APIKey$"
        - "^github.com/DataDog/datadog-api-client-go/v2/api/datadog\\.ServerVariable$"
        - "^gopkg.in/yaml.v3.Node$"

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: "satori's package is not maintained"
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: "gofrs' package is not go module"

    nakedret:
      max-func-lines: 0

    nolintlint:
      require-explanation: true
      require-specific: true

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

  exclusions:
    rules:
      - text: "exporting a pointer for the loop variable"
        linters: [exportloopref]
      - text: "Implicit memory aliasing in for loop"
        linters: [gosec]
      - source: "//noinspection"
        linters: [gocritic]
      - path: "_test\\.go"
        linters:
          - bodyclose
          - dupl
          - goconst
          - gosec
          - noctx
          - wrapcheck
      - text: "avoid meaningless package names"
        linters: [revive]

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
