// Package i18n provides internationalization support for Excel report generation.
package i18n

// Lang represents a supported language for report generation.
type Lang string

// Supported languages.
const (
	LangEN Lang = "en"
	LangJA Lang = "ja"
)

// Messages holds all translatable strings used in the Excel report.
type Messages struct {
	ReportDescription   string
	GeneratedBy         string
	NewSLO              string
	HeaderName          string
	HeaderSLO           string
	HeaderNewSLO        string
	HeaderSLIMin        string
	HeaderSLIAvg        string
	HeaderGoodQuery     string
	HeaderTotalQuery    string
	HeaderNewGoodQuery  string
	HeaderNewTotalQuery string
	ReportTitle         string
}

// Headers returns the column headers as an ordered slice.
func (m *Messages) Headers() []string {
	return []string{
		m.HeaderName,
		m.HeaderSLO,
		m.HeaderNewSLO,
		m.HeaderSLIMin,
		m.HeaderSLIAvg,
		m.HeaderGoodQuery,
		m.HeaderTotalQuery,
		m.HeaderNewGoodQuery,
		m.HeaderNewTotalQuery,
	}
}

var translations = map[Lang]*Messages{
	LangEN: {
		ReportDescription:   "SLO Report for %s\nList of SLOs that have never been below %g%% in %g days and 50%% of the total window has a negative error budget",
		GeneratedBy:         "Generated by Vigil https://github.com/rluisr/vigil",
		NewSLO:              "New SLO",
		HeaderName:          "Name",
		HeaderSLO:           "SLO",
		HeaderNewSLO:        "New SLO",
		HeaderSLIMin:        "SLI Min",
		HeaderSLIAvg:        "SLI Avg",
		HeaderGoodQuery:     "GoodQuery",
		HeaderTotalQuery:    "TotalQuery",
		HeaderNewGoodQuery:  "New GoodQuery?",
		HeaderNewTotalQuery: "New TotalQuery?",
		ReportTitle:         "SLO Report",
	},
	LangJA: {
		ReportDescription:   "SLO レポート: %s\nエラーバジェットが %g%% を %g 日間下回ったことがない SLO、及びウィンドウ全体の 50%% 以上でエラーバジェットが負の SLO 一覧",
		GeneratedBy:         "Vigil により生成 https://github.com/rluisr/vigil",
		NewSLO:              "新 SLO",
		HeaderName:          "名前",
		HeaderSLO:           "SLO",
		HeaderNewSLO:        "新 SLO",
		HeaderSLIMin:        "SLI 最小",
		HeaderSLIAvg:        "SLI 平均",
		HeaderGoodQuery:     "GoodQuery",
		HeaderTotalQuery:    "TotalQuery",
		HeaderNewGoodQuery:  "新 GoodQuery?",
		HeaderNewTotalQuery: "新 TotalQuery?",
		ReportTitle:         "SLO レポート",
	},
}

// Get returns the Messages for the specified language.
// Falls back to English if the language is not found.
func Get(lang Lang) *Messages {
	msgs, ok := translations[lang]
	if !ok {
		return translations[LangEN]
	}

	return msgs
}
